### PR TITLE
Add CMake support, tested on Ubuntu 16.04

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by tfogal** [comment]
Hi Daniel,

Modulo a couple technical questions, this is great (thanks!).
One thing I would ask: we actually had CMake files in the repo before, and it confused people because they expected them to work.  Would you be so kind as to make a 'contrib' directory and put it under there?
You could make it work straight from there, or I'd be happy to note the CMake support in the README.md.

**Comment by tribal-tec** [comment]
Hi Tom,

thanks for your quick reply!

Not sure I fully understand your concern, but putting the (top-level) CMakeLists.txt in a subfolder makes it hard to add Tuvok as a subproject with ```add_subdirectory(Tuvok)``` which was what we and probably other CMake users usually do.

I suggest to mention in a README.cmake the fact that the CMake build might not work and we can mention our mailing list for support, which we are happy to provide. Hence, the README.md will emphasize that the qmake and vcproj builds are the official supported ones.

**Comment by tfogal** [comment]
Hi, sorry for the delayed reply.
Okay, understood about the `add_subdirectory` concern.  My concern is that nobody reads READMEs ;-).  Could we have something in the CMake itself?

Maybe a
```cmake
message(WARNING "Building Tuvok for ImageVis3D is only supported through the qmake build.  This build is for embedded Tuvok; see the <blah> mailing list for support.")
```
?  You could wrap it in an `if(not some_invented_variable)` that you could set before `add_subdirectory(tuvok)`, to prevent it from annoying your users.

Would be happy to merge that.

**Comment by tribal-tec** [comment]
Hi, sorry as well for the delayed reply :)

I incorporated your request, seems the most elegant to me as well. Happy to see this merged, so we can get rid of our fork.

**Comment by tfogal** [comment]
LGTM.  Thanks!

**Pull request merged**
